name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install
        poetry lock
    - name: Run tests
      run: poetry run pytest
    - name: Run pre-commit
      run: |
        poetry run pre-commit install
        poetry run pre-commit run --all-files
